### ISSUE TITLE
Nanswap deep-linking isn't working

### ISSUE THREAD

**Issue by geommr** [perishllc/nautilus#2]
Not sure if it's a problem on Nanswap's side or if it's the in-app browser in Nautilus, but trying to swap and clicking 'Open wallet' returns a 'Web page not available' error (ERR_UNKNOWN_URL_SCHEME to be exact).

**Comment by fossephate** [comment]
Thanks for the report, I'll look into it as soon as I can!

**Comment by fossephate** [comment]
Temp fix in 0.5.9, but a larger fix that doesn't show the error page will come later
