### ISSUE TITLE
Random crashing on startup on android

### ISSUE THREAD

**Issue by geommr** [perishllc/nautilus#4]
Nautilus crashes randomly sometimes on startup and keep crashing afterwards until I clear app data (no errors or anything to report sadly). Not sure if it's an issue on my phone, but it's only been happening with Nautilus.
Running the latest version on Pixel 7.
It may be happening after getting updated, gonna wait on the next release to confirm.

**Comment by fossephate** [comment]
🤔 depending on what version you were on before, it may be a broken upgrade path
I suggest uninstalling and re-installing and see if that fixes the issue
going to the advanced settings and pressing the "Reset the app" button might also fix things

**Comment by geommr** [comment]
Reset the app seems to have fixed it, thanks!
